[2025-04-05T10:51:11.011+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: descargar_y_ver_dataset.mostrar_head manual__2025-04-05T10:51:06.293265+00:00 [queued]>
[2025-04-05T10:51:11.015+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: descargar_y_ver_dataset.mostrar_head manual__2025-04-05T10:51:06.293265+00:00 [queued]>
[2025-04-05T10:51:11.015+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2025-04-05T10:51:11.016+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2025-04-05T10:51:11.016+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2025-04-05T10:51:11.020+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): mostrar_head> on 2025-04-05 10:51:06.293265+00:00
[2025-04-05T10:51:11.023+0000] {standard_task_runner.py:54} INFO - Started process 640 to run task
[2025-04-05T10:51:11.025+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'descargar_y_ver_dataset', 'mostrar_head', 'manual__2025-04-05T10:51:06.293265+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/ml_dust_pred_dag.py', '--cfg-path', '/tmp/tmpriu0wfp9']
[2025-04-05T10:51:11.025+0000] {standard_task_runner.py:83} INFO - Job 12: Subtask mostrar_head
[2025-04-05T10:51:11.026+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/ml_dust_pred_dag.py
[2025-04-05T10:51:11.133+0000] {task_command.py:384} INFO - Running <TaskInstance: descargar_y_ver_dataset.mostrar_head manual__2025-04-05T10:51:06.293265+00:00 [running]> on host 6d3c9c1b3c45
[2025-04-05T10:51:11.159+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=descargar_y_ver_dataset
AIRFLOW_CTX_TASK_ID=mostrar_head
AIRFLOW_CTX_EXECUTION_DATE=2025-04-05T10:51:06.293265+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-04-05T10:51:06.293265+00:00
[2025-04-05T10:51:11.160+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ml_dust_pred_dag.py", line 16, in leer_y_loguear
    parse_dates=['date']
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 156, in __init__
    self._validate_parse_dates_presence(self.names)  # type: ignore[has-type]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 277, in _validate_parse_dates_presence
    f"Missing column provided to 'parse_dates': '{missing_cols}'"
ValueError: Missing column provided to 'parse_dates': 'date'
[2025-04-05T10:51:11.164+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=descargar_y_ver_dataset, task_id=mostrar_head, execution_date=20250405T105106, start_date=20250405T105111, end_date=20250405T105111
[2025-04-05T10:51:11.168+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 12 for task mostrar_head (Missing column provided to 'parse_dates': 'date'; 640)
[2025-04-05T10:51:11.206+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2025-04-05T10:51:11.215+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
